### ISSUE TITLE
Self Moderation - Introduction (Spam Posts, Block Users)

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#104]
The account object (saved to state) should look something like (stay consistent with whatever naming convention is being used throughout project):
```js
{
	// ...
	moderation: {
		blockUsers: [
			"alice:EOS8YDTmZcDMHZP8DgBSeFXRvLiQP6XxWP78ThaciDF4eVXZxw1Sk",
			"bob:EOS8meyWrgjDmoNZwEfKKsgcrirY3JPX3FsUPniDnJwpfgpoa2E7a"
		]
		blockPosts: [
			201912: [
				"8908db5838c61834c7e0c05fc1fd6fffa30a86acd4f48a366594ac4b7c3d7601"
			]
		]
	}
}
```

Users should be able to block a user from their profile and block a post via mark spam. A user can be unblocked either in the moderation panel, or also on their profile. A post must be unblocked in the moderation panel -- we'll discuss later how the UI/UX for the panel regarding posts will look.

**Comment by samosaboy** [comment]
Added in d839d624e32f992406104267b3c3a04f62e0304f
