### ISSUE TITLE
Self Moderation - "Display Blocked Content" setting

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#105]
There should be a setting which allows some slight variance on how blocked/moderated content is treated: Hidden, Collapsed/Warned

By default, this should be set to Hidden.

# Hidden

Pretend the content isn't there when in the tag view. If the moderated content is a reply, then the post as well as any replies to it should also be hidden.

# Collapse/Warned

A warning should be presented to the user that there is content is spam, but the content is still visible to the user. In the case of if the moderated content is a reply, then the reply is auto-collapsed. The replies to the moderated content do not need to also be auto-collapsed as they will be hidden if the moderated content is collapsed. **Content should indicate who (the post key) moderated the content**

-----

There should also be a toggle on/off feature of "Unsigned posts are spam" which should be toggled to true by default. This setting is mentioned in #106 .

**Comment by samosaboy** [comment]
Added in:

80a5aa89361506868bfd94618ee3aec40923a553
ae2c5ef61a31dab4906cb01d2568ec0467c863ad
e72040a30d6e0e50a45d64e610521fb59804f8e1
97a3b850989b42ecede3b158c1c5ae273467d941
