### ISSUE TITLE
Delegated Moderation

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#106]
Further extend the moderator object as,

```js
{
	// ...
	moderation: {
		// ...
		delegated: {
			"all": [ "alice:EOS8meyWrgjDmoNZwEfKKsgcrirY3JPX3FsUPniDnJwpfgpoa2E7a" ]
			"eos": [ "bob:EOS8YDTmZcDMHZP8DgBSeFXRvLiQP6XxWP78ThaciDF4eVXZxw1Sk" ]
		}
	}
}
```

where the keys of "delegated" are the tags that a given account's (public key) settings will be borrowed for moderation. You should be able to add someone as a moderator, or remove them from the moderator settings panel.

Consider, in your moderator service that it should have:

```js

async function isBlockedUser(p: Post) : Promise<boolean> {
	// ...
}

async function isBlockedPost(p: Post) : Promise<boolean> {
	if (settings.unsignedPostsAreSpam && !p.pub)
		return true;
	// ...
}


async function isBlocked(p: Post) : Promise<boolean> {
	return (await this.isBlockedUser(p)) ||
		(await this.isBlockedPost(p));
}
```

In isBlockedUser and isBlokedPost we will check to see is a user/post is blocked using both the local (self) moderator settings, as well as the settings borrowed from any delegated moderators. An API will be provided to help with look up of this data.

**Comment by samosaboy** [comment]
Added in 74402fd38dcced8986bbd27dcc7bd1bd19ef23b7
