### ISSUE TITLE
Some formatted text disappears when editing. 

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#114]
Quoted and list texts disappear when entering into edit mode:

![ezgif-3-85459259fbe8](https://user-images.githubusercontent.com/14120416/72461525-1b0bd000-37c7-11ea-8667-3028d808ab9f.gif)

**Comment by samosaboy** [comment]
Fixed in 903017ce6639e3e768c29454d00c0632b2f1187d
