### ISSUE TITLE
Creating a new post hangs with post spinner

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#115]
![image](https://user-images.githubusercontent.com/39639828/72487677-a3887180-37c3-11ea-995c-319bb92730da.png)

```
no poster found, posting as anon!
transaction set: ! 761ce8c8ec8d75afee5a89bf206b22cefecff036589ca2806770be0ec73eb093
```

The thread was created successfully, and going to `#test` it can be seen fine. Not sure why this occurs. Have tested twice.

**Comment by samosaboy** [comment]
Seems have to been resolved as of the recent deploy.
