### ISSUE TITLE
Double editing issue

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#116]
Below contains 3 edit transactions that occurred in order:

1. https://eosflare.io/tx/7B4760CDCEED9A4EFFA652A7249A8E3E6E1AB8A1AA6DFC5174DC73BAE38EC415
2. https://eosflare.io/tx/0DD01AAC949BD5AB0DFA5236F56DE52DD3DE67D0B834C9AEA1128AA872A8E400
3. https://eosflare.io/tx/138CD23E45081E3F0549A5229AF6F1BE43E9B3CE2930A5DA4F44AA5FA2DD51E6

Edit [2] was made directly after [1] was successful and the green prompt indicating a successful edit was made. However, this resulted in the spinner hanging and the edit never actually going through despite hitting chain. Edit [3] was made by refreshing the page, which showed the changes of Edit [1] but not [2] on the page. Edit [3] worked successfully, and remained successful after a page refresh.

Notice in the case of [2] the following:

```
  "threadUuid": "095671e4-e310-4d90-8a0e-2d712da81938",
  "parentUuid": "1673db3d-f285-44ff-b14e-755bc05508f8",
```

What this means is when an edit is preformed, the post's uuid is being updated with the edits uuid, however, this behavior is **incorrect**. The UUID of the post **does not change** with the edit, despite edits having their own UUID. This is why after refreshing the page, Edit [3] worked correctly, because the post's UUID was correct.

**Comment by samosaboy** [comment]
Seems to have been fixed in the recent deploy.
