### ISSUE TITLE
Always sanity check tags field of a post before posting

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#117]
See the post,

https://eosflare.io/tx/21A866A2F656BD2014C900E928C2F2583AFF41A9BDB369EBD1767D5BF2BED2DD

which has "#charts" which should be "charts" -- I'm not sure yet how this user made this post, once I have the details, I will update this issue further.

**Comment by Novusphere** [comment]
Add sanity check here too:
![image](https://user-images.githubusercontent.com/39639828/72488772-c9634580-37c6-11ea-94f6-51ed98f60ea9.png)

**Comment by Novusphere** [comment]
which would prevent this, too:
![image](https://user-images.githubusercontent.com/39639828/72488791-e0099c80-37c6-11ea-910b-927df9dbad85.png)

**Comment by samosaboy** [comment]
Fixed in 1ce4ee9682bd1da1e01a813115255184a8548a18
