### ISSUE TITLE
UIDW: Transfer/Withdraw should require user to re-enter their discussions account password

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#125]
The wallet private key **should not** under any circumstances be stored in local storage or persistently. It should be derived from the encrypted brain key / seed as required when the user enters their password.

**Comment by samosaboy** [comment]
Done in e8c61576cc5eb85f334067dfe50bffbb4990f268,  81e712c566769c0cc1c917db89d8acd1b976f618
