### ISSUE TITLE
UI/UX Improvements

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#126]
- Remove "disconnect wallet" from drop down
- Rename "connect wallet" to "connections" (take to Settings > Connections)
- Rename "deposit" to "wallet" (take to Settings > Wallet)

Only display balances above 0 (in drop down), and balances should be the same as clicking "wallet"

So the drop down should look like:

- Logout
- Profile
- Settings
- Connections
- Wallet
- [ ... non-zero balances ... ]

Remove everything in "Connections", add the ability to Connect/Disconnect your EOS account there. Display the account name if it's connected.

Refresh UIDW balances automatically every 15s and include a manual "Refresh" icon beside "Balances" -- wait 5s after a successful transaction (deposit, withdrawal, transfer) and automatically refresh balances.

Remove "Memo ID" field from UIDW deposit

For UIDW Transfer and Withdrawal:
Display amount, fee and total amount.

- User enters amount, system computes fee & total amount
- User enters total amount, system computes fee & amount

**Comment by samosaboy** [comment]
Done.
