### ISSUE TITLE
Capitalize "Home" and Drop down Menu

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#127]
![image](https://user-images.githubusercontent.com/39639828/72582087-9d6fbf00-38af-11ea-9eeb-6070ab16408d.png)

**Comment by Novusphere** [comment]
Logout Profile Settings

etc...

**Comment by samosaboy** [comment]
Fixed in ed5e31814e9d8819b27fb8dc98c5711bf596de72
