### ISSUE TITLE
Weird issue with Settings?

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#129]
![](https://media.discordapp.net/attachments/584804633986203696/667576141879574559/Screenshot_2020-01-16_19.48.32.png)

Not sure how to reproduce...

**Comment by Novusphere** [comment]
![image](https://user-images.githubusercontent.com/39639828/72584118-cba4cd00-38b6-11ea-96ed-a1ff41689627.png)

**Comment by samosaboy** [comment]
Fixed in f412ca4f3c27d65aa8b2b858c7f1b4231f75fd79
