### ISSUE TITLE
Updates to Profile

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#132]
![image](https://user-images.githubusercontent.com/39639828/72584615-c2b4fb00-38b8-11ea-824a-ceca236bb096.png)

Remove filler text for Contacts and Connected Accounts and Following

Add section **Wallet** and display the users UIDW public key. This can be obtained from their post history. If the user has never posted before, then nothing should be displayed under Wallet. See #130 

Change Followers to 0 (filler).

**Comment by samosaboy** [comment]
Added the section but once creating posts/editing is fixed this won't work.

**Comment by samosaboy** [comment]
Added in 98b696f7bef06eee11b82cba6060dfe2d01ad98a
