### ISSUE TITLE
UIDW Issues

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#133]
Correct for precision (for amount, fee, and total amount they all should have the same precision).

![image](https://user-images.githubusercontent.com/39639828/72585272-6e5f4a80-38bb-11ea-9837-373f67b02c6a.png)

Enforce http://atmosdb.novusphere.io/unifiedid/p2k "min" field client side. "min" refers "amount" being sent not the total.

Memos are not a required field!

Properly display error messages as to why a transfer/withdrawal fails, example:
```
{error: true, message: "Error: Minimum transfer/withdrawal is 1 ATMOS"}
```
Currently it just says it failed, not why...

**Comment by samosaboy** [comment]
Fixed in 2337da911edbaf70b452af8840a31b1f156624e6
