### ISSUE TITLE
missing part of the text editor

### ISSUE THREAD

**Issue by fixedelineation** [Novusphere/discussions-app#134]
<img width="425" alt="Screenshot 2020-01-16 21 19 48" src="https://user-images.githubusercontent.com/17442082/72586292-0b16ed80-38a6-11ea-8cfa-a83c21148d12.png">

there is a space between the quote and the link button that appear to be hot. one part adds a bullet and the other does nothing but gets outlined in  a square made from dotted lines
<img width="384" alt="Screenshot 2020-01-16 21 22 23" src="https://user-images.githubusercontent.com/17442082/72586373-4fa28900-38a6-11ea-99bf-23bb68d36e55.png">

**Comment by samosaboy** [comment]
Fixed in 903017ce6639e3e768c29454d00c0632b2f1187d
