### ISSUE TITLE
Add ability to send to UIDW key in Airdrop

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#137]

**Comment by Novusphere** [comment]
10,gux
10,PUBLICKEY

10,gux does transfer(eos.account, gux, 10 atmos, memo)
10,PUBLICKEY does transfer(eos.account, nsuidcntract, 10 atmos, PUBLICKEY)
so the only thing you need to really do is add handling for looking up if there's a p2k entry for the token being airdropped.

Then, if a public key is used instead of an account the "to" is the p2k contract and the memo is the public key.

**Comment by samosaboy** [comment]
Added in https://github.com/Novusphere/discussions-app/commit/4b1484e47d68861117d96f47e0f4d2a70c93b2fe
