### ISSUE TITLE
Amount/Fee for tips is incorrect

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#139]
Currently, the amount the tipper writes, i.e. `#tip 1 ATMOS` is being used as the **amount**. But this is wrong, it should be used as the **total Amount**, so when a person does `#tip 1 ATMOS` the person being tipped receives 0.999 and the fee is 0.001 since ATMOS fee is currently set to 0.1%

**Comment by samosaboy** [comment]
Fixed in 9197d25bed36c094ff90c2fd51af5c8d4f9f9887
