### ISSUE TITLE
Password not recognized

### ISSUE THREAD

**Issue by fixedelineation** [Novusphere/discussions-app#14]
Login via brainkey requires typing out brainkey. Password isn't recognized
<img width="1110" alt="Screenshot 2019-10-18 10 55 31" src="https://user-images.githubusercontent.com/17442082/67117163-d1472580-f196-11e9-9525-bf648289afcc.png">

**Comment by Novusphere** [comment]
related #21

**Comment by samosaboy** [comment]
Fixed in https://github.com/Novusphere/discussions-app/commit/5aa658bdad50e7cc0e64c2c13ed100242d6ecc58
