### ISSUE TITLE
Upvoting for Unified ID

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#144]
For an initial vote, we combine this with the `/post` call by adding a new field `vote` to the `data` object. The `vote` field looks like:

```js
vote: {
	voter: '',
	uuid: p.uuid,
	value: 1,
	metadata: JSON.stringify({
		nonce: number,
		pub: p.pub,
		sig: p.voteSig
	})
}
```

nonce must be higher than the nonce used in the previous vote, so it's fine to use time for this field.
`voteSig` is as follows:
```js
const hash0 = ecc.sha256(`${value} ${uuid} ${nonce}`);
```

and then use `ecc.sign()` with the post private key. `value` is the vote value which in the case of an initial post is always 1 (self up vote).

**Note:** A down vote is -1, a neutral vote (unvoting) is 0.

-----

For changing a vote, use the endpoint `/vote` which takes a `data=` string similar to other endpoints with the encoded value being the same as the `vote` field from the `/post` endpoint.

**Comment by Novusphere** [comment]
- Assume vote always succeeds, don't wait to colorize what option they chose
- Post they voted on needs to update it's vote value
- Post's seem like they only factor in `upvotes` right now when it should be `upvotes-downvotes` for vote value

**Comment by samosaboy** [comment]
Added in 789c70de68abefe249541610ab506c406dad3dac

Cannot fix upvoting/downvoting without myVote being finished.
