### ISSUE TITLE
Overlapping txt

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#148]
![Screen Shot 2020-01-22 at 3 04 25 PM](https://user-images.githubusercontent.com/14120416/72905571-a7b71080-3d28-11ea-8d25-06409c014438.png)

**Comment by samosaboy** [comment]
Should be fixed in https://github.com/Novusphere/discussions-app/commit/f0ee7ffc681b16cfc84286045cf7486bd29a5066
