### ISSUE TITLE
Searching for users 

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#149]
A search for a user's display name should bring up a preview of their profile that includes their public key for easy data collection.

**Comment by Novusphere** [comment]
Where would searching for users be preformed from?

**Comment by bluabaleno** [comment]
from the search bar

**Comment by Novusphere** [comment]
How would we know whether they were searching for a post or searching for a user instead of post content? Right now, there's no limitations on display name lengths, or characters AFAIK so for example, my name could be "xia xia xia" (with spaces).

**Comment by bluabaleno** [comment]
We could do "@user" search.

**Comment by Novusphere** [comment]
Great idea.

**Comment by Novusphere** [comment]
Superseded by #163
