### ISSUE TITLE
Brainkey account shows up as eosforumanon

### ISSUE THREAD

**Issue by fixedelineation** [Novusphere/discussions-app#15]
Made a post using brainkey account 5dollarATMOS
https://testd2.discussions.app/e/general/2hpbg107hawms/Testing

shows up as eosforumanon user
<img width="839" alt="Screenshot 2019-10-18 11 05 41" src="https://user-images.githubusercontent.com/17442082/67117385-69450f00-f197-11e9-89b5-edcad7016189.png">

**Comment by fixedelineation** [comment]
<img width="836" alt="Screenshot 2019-10-18 11 09 28" src="https://user-images.githubusercontent.com/17442082/67117566-df497600-f197-11e9-8b3c-e2cb2de58f7c.png">
just made the post and it shows up as anon

**Comment by Novusphere** [comment]
related #22

**Comment by samosaboy** [comment]
Fixed in https://github.com/Novusphere/discussions-app/commit/82904ec8bbd86b658cf30467cad94b13088717b0
