### ISSUE TITLE
"Fake Success" when depositing

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#151]
If a user closes their Scatter/EOS Wallet and the connect is broken, Discussions still thinks it's connected. Obviously, when `eos.transact()` is called, it fails and returned `undefined` for the transaction id. When depositing, if the result is `undefined`, then we know the connection is broken and we should prompt an error telling the user to reconnect their wallet.

Currently, it gives a success message with the link:
https://bloks.io/transaction/undefined

**Comment by Novusphere** [comment]
Also, when Errors like this occur when Depositing, they should be displayed:

https://cdn.discordapp.com/attachments/584804633986203696/669787020155158548/unknown.png

This is an error that occurs after calling `eos.transact()`

**Comment by samosaboy** [comment]
Fixed in f5901092a1f4b2f5e47afd3eeeed294187f9569a
