### ISSUE TITLE
Formatting lost when updating post.

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#153]
![ezgif-7-4aaecd15f12a](https://user-images.githubusercontent.com/14120416/73000704-2d09f600-3df9-11ea-8adf-788affb712a4.gif)

**Comment by bluabaleno** [comment]
console data 

<img width="1552" alt="Screen Shot 2020-01-23 at 4 02 40 PM" src="https://user-images.githubusercontent.com/14120416/73001119-d9e47300-3df9-11ea-8df1-82742a21a59c.png">

**Comment by samosaboy** [comment]
This is an issue with nested lists using Quill Editor

https://codepen.io/voziv/pen/rmpVZb/

^ This example shows that nested lists are not supported as quill uses `classNames` to separate indent levels for a list.

Solution: find a module/implement nested lists or use another editor.

**Comment by bluabaleno** [comment]
hmm... it seems like this is not just a problem with our site...

Maybe it's because the fact I've copied and paste the text from Medium.

**Comment by bluabaleno** [comment]
Editor problem persists with new OS and browser, with content that is natively written in editor.

**Comment by samosaboy** [comment]
Hey @bluabaleno can you be more specific, is it still the same nested list issue?

**Comment by Novusphere** [comment]
According to @bluabaleno this has been resolved, closing.

**Comment by bluabaleno** [comment]
hmmmm I seem to be having the same issue again. 

I copied over some txt from Google docs and all the indentations have collapse to single level.
In the editor:
<img width="1552" alt="Screen Shot 2020-02-26 at 7 20 09 PM" src="https://user-images.githubusercontent.com/14120416/75379411-3ccf9b00-58cd-11ea-92ab-6b11aa749547.png">
In the preview:
<img width="1552" alt="Screen Shot 2020-02-26 at 7 20 17 PM" src="https://user-images.githubusercontent.com/14120416/75379428-46590300-58cd-11ea-87fb-e42b28567bb7.png">
