### ISSUE TITLE
Telegram embed issue

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#158]
This shouldn't have tried to embed:
`Telegram: [https://t.me/eosdiscussionsapp](https://t.me/eosdiscussionsapp)`

From:
https://beta.discussions.app/tag/discussions/859or1wz5pz9/discussions_2_will_launch_on_january_27_2020

**Comment by samosaboy** [comment]
Fixed in 3ba9894dc85bac845dfcc8ade6f25fcfd2395fe9
