### ISSUE TITLE
visual bug

### ISSUE THREAD

**Issue by fixedelineation** [Novusphere/discussions-app#16]
The side bar has some issues in chrome Version 77.0.3865.90 (Official Build) (64-bit)
<img width="410" alt="Screenshot 2019-10-18 11 04 47" src="https://user-images.githubusercontent.com/17442082/67117463-9b567100-f197-11e9-959f-a540c2025a26.png">

**Comment by Novusphere** [comment]
These are icons that aren't loading / obsolete, assuming you're referring to UXFyre
