### ISSUE TITLE
Use static file "site.json" to determine settings

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#160]
Note that multiple domains, e.g. "discussions.app", "eos.discussions.app" all might point to the same running instance. To determine which correct settings to use we refer to "site.json" and access the first-child key based on `window.location.host.toLowerCase()`

Whenever a user changes pages, a random image from `bannerImages` is chosen.

By default, a user is subscribed to **no tags.**
If a user is subscribed to no tags, then their "Home" is the same as "All" -- otherwise, their Home should only show tags they're subscribed to.

Their left bar should by default have home, feed all, then a separator, then any of the `defaultTagsGroups`, example:

```
Home
Feed
All
------
Politics
Technology
Social Media
[ Add a tag bar ]
[ ... Subscribed Tags ... ]
```

The default moderators should be set using `defaultModerators`.

**Comment by samosaboy** [comment]
Added in https://github.com/Novusphere/discussions-app/commit/837acfb91b3175829e51fdcbcbcead1bf1641382
