### ISSUE TITLE
Search for a user

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#163]
When a user search begins with "@" attempt to find users with similar display names,

i.e. searching "xia" should perform a regular search as the search bar currently does,
but searching "@xia" should perform a user search.

**Comment by Novusphere** [comment]
http://atmosdb.novusphere.io/discussions/search/user?domain=https://discussions.app&name=xia

Similar to https://discussions.app/trending the search results should be formatted similarly. It should display the identicon for the user, their public key (pub field) as well as the other fields in the object. Fields followers, threads, and posts are currently always set to 0.

@samosaboy

**Comment by samosaboy** [comment]
Added in https://github.com/Novusphere/discussions-app/commit/6936bd1d223f88f57600e223831c6c7c4c7b83f8
