### ISSUE TITLE
Upload Images

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#164]
Limit is 1 MB

Endpoint: `https://atmosdb.novusphere.io/discussions/upload/`

Example:
```
 <!--  SINGLE FILE -->
<form action="https://atmosdb.novusphere.io/discussions/upload/" enctype="multipart/form-data" method="POST"> 
   <input type="file" name="image" />
   <input type="submit" value="Upload a file"/>
</form>
```

Returns:
```
{"filename":"1579832397996.png"}
```

Url is then:
http://atmosdb.novusphere.io/discussions/upload/image/1579832397996.png

**Comment by samosaboy** [comment]
Added in https://github.com/Novusphere/discussions-app/commit/015205f79320cd841de085e94a1d7f734dad9def
