### ISSUE TITLE
Don't parse for tips in an edit

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#166]
Even if the original comment was "nice #tip 1 ATMOS" and the new comment is "nice #tip 1 ATMOS # tip 1 EOS" the "#tip 1 EOS" should not be processed.

You cannot tip in an edit.

**Comment by samosaboy** [comment]
Fixed in https://github.com/Novusphere/discussions-app/commit/82ed6902ede1b41650c8ea0366076a08a5adfc3e
