### ISSUE TITLE
Populate tag on-hover information

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#167]
For description/icons, utilize site json:

![image](https://user-images.githubusercontent.com/39639828/73128214-fddeba80-3f99-11ea-91e9-ef38d1190247.png)

![image](https://user-images.githubusercontent.com/39639828/73128221-0b944000-3f9a-11ea-9cf3-299cc7f60b39.png)

For member count, use:
`http://atmosdb.novusphere.io/discussions/site/members/eos` (example)

Note that currently, this endpoint always return 0 and isn't "functionally" implemented.

Remove "online"

**Comment by samosaboy** [comment]
Added in https://github.com/Novusphere/discussions-app/commit/d72ad115a47fca4bc2b410c08b12261758efb439
