### ISSUE TITLE
Copy and pasting a from an existing tip comment completely bugs out

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#169]
It seems if you copy-paste the tip, it doesn't work like, copy and pasting #tip 1 MPT #tip 1 BBT #tip 1 ATMOS from another post... you can see my message :

https://discussions.app/tag/blockchainnormies/w77zszhhgld3/the_blockchain_normie_voices_get_an_ceo_lynx_is_live_and_south_korean_military_uses_eosio#45b5afee-5ff9-48ee-a607-6b834a989e22

**Comment by samosaboy** [comment]
Fixed in https://github.com/Novusphere/discussions-app/commit/8140845c6b3a572f928438344a530aa20967745f
