### ISSUE TITLE
Followers on user profile

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#170]
Use endpoint
`http://atmosdb.novusphere.io/discussions/site/profile/EOS5FcwE6haZZNNTR6zA3QcyAwJwJhk53s7UjZDch1c7QgydBWFSe`

Note that currently, this endpoint always return 0 and isn't "functionally" implemented.

**Comment by samosaboy** [comment]
Fixed in https://github.com/Novusphere/discussions-app/commit/a9a16d0a5888c4362af99166ba4e16a618960434
