### ISSUE TITLE
Tipping BBT via UID doesn't seem to work

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#173]
<img width="1440" alt="Screen Shot 2020-01-26 at 7 05 48 PM" src="https://user-images.githubusercontent.com/14120416/73140275-110f8a00-406f-11ea-82cb-2b9e36a2fbc5.png">

**Comment by bluabaleno** [comment]
it's stuck on post

**Comment by Novusphere** [comment]
Resolved once tokens end point was corrected:

https://discussions.app/tag/test/3an06kiuxlnh4/block_base_white_paper_tl_dr_version#3b40955f-28ac-49b4-a571-26ac571cd416
