### ISSUE TITLE
Moderation - Pinning

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#175]
**Note**: Only thread pinning is high priority, reply pinning is not. Once thread pinning has been implemented this issue can be marked low priority.

Similarly how we store `blockedPosts` and `blockedUsers` in moderation, we need to store another value `pinnedPosts`. Similarly how a post can be marked as spam, it can also be pinned.

When it's pinned, it gets added t o `pinnedPosts` -- this array can work the exact same format/way that `blockedPosts` works by storing a partial url.

However, `pinnedPosts` should store relative to the tag, i.e.

```
"pinnedPosts": {
	"test": [
		"/tag/test/2u1swx8cwkncw/lorem_ipsum"
	]
}
```

When a user visits this tag if they (or their moderators) have pinned a post, then the pinned posts should appear at the start of the tag. 

Currently, we call `getPostsForTags()` but we also need to get the posts for an encoded Id, since this is the information we have from `pinnedPosts`. 

This is pretty simple to do, since we already do it here:
https://github.com/Novusphere/discussions-app/blob/master/novusphere-js/discussions/service/discussions.ts#L359

Using this we can implement a method
`async getPostForEncodedId(_id: string): Promise<Post>`

Then to go from the array in "test" to a Post[], we simply call `getPostForEncodedId()` for each Id.

**Comment by Novusphere** [comment]
# Handling pinning when the post is a reply:

Consider the following thread
```
op
|-a
|-b
|-c
|--d
|--e
|-f
```
Suppose `c` was pinned, it would look like
```
op
|-c
|--d
|--e
|-a
|-b
|-f
```
Suppose `c` and `e` were pinned it would look like
```
op
|-c
|--e
|--d
|-a
|-b
|-f
```
Suppose only `e` was pinned, it would look like
```
op
|-a
|-b
|-c
|--e
|--d
|-f
```

**Comment by samosaboy** [comment]
Re-opening because of replies are still todo.
