### ISSUE TITLE
Posts not updating onto home page/feed has 404 error

### ISSUE THREAD

**Issue by dblstacker** [Novusphere/discussions-app#18]
![image](https://user-images.githubusercontent.com/45493893/67250451-741ece80-f439-11e9-83ea-cfe32f0f381b.png)
![image](https://user-images.githubusercontent.com/45493893/67250488-9dd7f580-f439-11e9-819b-032f431d59a7.png)

**Comment by samosaboy** [comment]
This should be resolved in 7a795d8c207c1cae18b7931ac396270e2b3f1838
