### ISSUE TITLE
Firefox posting is broken due to #tip regex

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#199]
https://media.discordapp.net/attachments/628358780421406755/674307234829828096/unknown.png

https://media.discordapp.net/attachments/628358780421406755/674306866192449596/unknown.png

**Comment by samosaboy** [comment]
This should be resolved in https://github.com/Novusphere/discussions-app/commit/0b2b0cf5830550bfc2cc5576702217113f8ae63a
