### ISSUE TITLE
Random Logout

### ISSUE THREAD

**Issue by dblstacker** [Novusphere/discussions-app#20]
Occasionally, I get logged out when clicking the "home" button on the top left. It asks for my password when I logged in using Scatter.

![image](https://user-images.githubusercontent.com/45493893/67250706-70d81280-f43a-11e9-836f-c03e4371d776.png)

**Comment by samosaboy** [comment]
This might be related to missing pages prompting a restart of the entire app.

**Comment by samosaboy** [comment]
Haven't been able to replicate this since, so marking it as resolved for now.
