### ISSUE TITLE
Can't see instagram posts anymore?

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#200]
The post shows up in preview just not when I open them...
<img width="1440" alt="Screen Shot 2020-02-07 at 11 54 00 AM" src="https://user-images.githubusercontent.com/14120416/74027727-a0d30380-49a0-11ea-9040-af5b6e5bdef0.png">
<img width="1440" alt="Screen Shot 2020-02-07 at 11 53 52 AM" src="https://user-images.githubusercontent.com/14120416/74027737-a597b780-49a0-11ea-852a-492f1018294e.png">

**Comment by Novusphere** [comment]
Link to the post in question, note for @samosaboy embed is fixed by calling  `instgrm.Embeds.process()`

https://discussions.app/tag/potlaw/1fmnctyfi2l90/stfuf
