### ISSUE TITLE
Failed post

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#202]
<img width="1440" alt="Screen Shot 2020-02-10 at 3 37 05 PM" src="https://user-images.githubusercontent.com/14120416/74164138-442f4d00-4c1b-11ea-964e-d770b28648d3.png">

I tried logging out and logging back and that didn't work. 

It was a reply to the last post on this thread:
https://discussions.app/tag/coffee/2ec9qs24ohvfk/hello_coffee_viewers_a_warm_welcome_from_discussions_lets_kick_things_off_with_a_meme_contest_20_000_atmos_🤩_no_eos_account_required_to_enter

**Comment by Novusphere** [comment]
I wonder if the "##tip" is what caused the error, but please refrain from opening further issues regarding  "discussions.app" and only open new issues regarding beta.discussions.app

**Comment by bluabaleno** [comment]
gotcha. Huh yeah I didn't catch that.

**Comment by Novusphere** [comment]
This also might have had to do with the issues the EOS main net is currently having.
