### ISSUE TITLE
Followers incorrectly showing

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#207]
I noticed, http://atmosdb.novusphere.io/discussions/site/profile/EOS7yBvx7mSApiyKPWzgpU3Xs6Em66WhkdYpM9Exon4rmeikBefZf

but https://beta.discussions.app/u/shovel12-EOS7yBvx7mSApiyKPWzgpU3Xs6Em66WhkdYpM9Exon4rmeikBefZf shows 0 followers

**Comment by samosaboy** [comment]
fixed in  42d486173b2c8c2f3fe3519ba748d335a54c4ded
