### ISSUE TITLE
Data/login persistence errors pertaining to login

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#21]
Login as lmao11 with password lmao11
Logout (Disconnect)
Login - Brian Key - continue as lmao11
Enter lmao11 for password
"Incorrect brain key or password"
Again, i assume this relates to bugs that stem from logging in/out, etc.

**Comment by samosaboy** [comment]
Fixed in https://github.com/Novusphere/discussions-app/commit/5aa658bdad50e7cc0e64c2c13ed100242d6ecc58
