### ISSUE TITLE
Clicking on "Blocked" in settings crashes site.

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#210]

**Comment by samosaboy** [comment]
@bluabaleno just fixed it in https://github.com/Novusphere/discussions-app/commit/0b2b0cf5830550bfc2cc5576702217113f8ae63a

Can you check? I was unable to reproduce the bug but I did add a part to transform legacy users (from old site).

**Comment by bluabaleno** [comment]
Just checked it, and it's still crashing for me.

![ezgif-7-64155d9f0dba](https://user-images.githubusercontent.com/14120416/74432884-3fef7380-4e57-11ea-8e81-46782f4bc048.gif)

**Comment by samosaboy** [comment]
I ses this is on the old site, do you experience this issue on beta?

________________________________
보낸 사람: bluabaleno <notifications@github.com>
보낸 날짜: Thursday, February 13, 2020 6:52:22 AM
받는 사람: Novusphere/discussions-app <discussions-app@noreply.github.com>
참조: Nikunj Varshney <varshney.nikunj@gmail.com>; Comment <comment@noreply.github.com>
제목: Re: [Novusphere/discussions-app] Clicking on "Blocked" in settings crashes site. (#210)


Just checked it, and it's still crashing for me.

[ezgif-7-64155d9f0dba]<https://user-images.githubusercontent.com/14120416/74432884-3fef7380-4e57-11ea-8e81-46782f4bc048.gif>

**Comment by bluabaleno** [comment]
nope, no issues there
