### ISSUE TITLE
Image upload does not insert a link but plain text

### ISSUE THREAD

**Issue by samosaboy** [Novusphere/discussions-app#213]
As a result the "click to open image" functionality does not work.

**Comment by Novusphere** [comment]
Can we not make it so all inlined images (images that are just links) are automatically clickable when transformed into their img src tags? This way, not only uploads are clickable, but all inline images.

**Comment by samosaboy** [comment]
They are clickable already: https://discussions.app/tag/challenge/k4mk2gk79qge/challenge_eos_app_rewarding_the_top_100_active_users

Added so when an image gets uploaded, it converts to a link instead of plain text. This has fixed this bug.
