### ISSUE TITLE
error message on login 

### ISSUE THREAD

**Issue by fixedelineation** [Novusphere/discussions-app#215]
![Screen Shot 2020-02-17 at 7 42 58 AM](https://user-images.githubusercontent.com/17442082/74671231-8eef1e80-515f-11ea-8885-4649bcdf3e40.png)
Getting this message upon login, also one about unable to sync but i'm not fast enough to screen shot.

**Comment by Novusphere** [comment]
Does signing out / signing back in resolve the issue?

**Comment by fixedelineation** [comment]
The error doesn't appear to cause any problems, and when signing out and back in it doesn't show up again. Im not sure its a real error since using the site doesn't seem to be affected.

**Comment by Novusphere** [comment]
This likely had to do with migrating when we changed the account system.
