### ISSUE TITLE
Tip parser incorrectly parsing non existent tips

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#217]
See https://eosflare.io/tx/428C60CDCC5F78A2D0CD86D7137918AB6732650659EAB163DEEBBAB77385C779

which parsed tipping 10 EOS twice from the post.

**Comment by Novusphere** [comment]
https://discussions.app/tag/coffee/2ec9qs24ohvfk/hello_coffee_viewers_a_warm_welcome_from_discussions_lets_kick_things_off_with_a_meme_contest_20_000_atmos_%F0%9F%A4%A9_no_eos_account_required_to_enter#05419982-3cbd-49dd-8e23-52de815f8182

**Comment by samosaboy** [comment]
Fixed
