### ISSUE TITLE
Improvements visual feedback when a tip is being made in a post

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#218]
Currently, when a post is made you're required to enter your password.

It would be great if on this screen it could provide a breakdown of all the outgoing transfer (tips) that are occurring in the transaction. This way, in the case of our previous parsing issue which had a post send the same tip twice this could have been visually caught by the user and the transaction canceled.

**Comment by Novusphere** [comment]
Example shown of better summary of transaction:
![image](https://user-images.githubusercontent.com/39639828/76468513-7d95dc80-63c2-11ea-860c-471319d8e539.png)

**Comment by samosaboy** [comment]
Added in https://github.com/Novusphere/discussions-app/pull/285
