### ISSUE TITLE
displayName not correctly being set in non-Scatter posts

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#22]
Signed in as test11 with password test11 (used brain key)
Went to https://testd2.discussions.app/e/uxfyre/527hsud8oqmh/Hey_guys and made a post
Post had no name
Refreshed - Post shows up as eosforumanon
Transaction shows displayName was not set in metadata: https://eosq.app/tx/f8a48f2071211bc19f597e39522c273f756f2b299f98c21121eaf7cb6e6563d4

**Comment by samosaboy** [comment]
This is fixed in https://github.com/Novusphere/discussions-app/commit/82904ec8bbd86b658cf30467cad94b13088717b0
