### ISSUE TITLE
Ability to sort content

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#221]
Add functionality to sort content by: Popular, Controversial, Recent.

We define two variables:
- T: The time since the post has occurred in hours
- G: A gravity constant of 1.8

We define Popular as ordering by score descending:
```
score = (upvotes-downvotes)/((T+2)^G)
```

We define Controversial as ordering by score descending:
```
score = (upvotes+downvotes)^(downvotes/upvotes)/((T+2)^G)
```

We define Recent as ordering by score ascending:
```
score = T
```

Scoring algorithms should be implemented on the back end and the client should provide a parameter `sort` with the string `popular`, `controversial` or `recent`, by default `popular` is used if no string is specified.

**Comment by Novusphere** [comment]
Backend tag has been removed, front end integration remains.

For sorting, you can now include a new parameter `sort:
https://github.com/Novusphere/discussions-app/blob/master/novusphere-js/discussions/service/discussions.ts#L569

e.g.

`{ sort, key, cursorId, ... }`

So: https://github.com/Novusphere/discussions-app/blob/master/novusphere-js/nsdb.ts#L7

Should add `sort?: string`

When you specify `sort` as part of thee `INSDBQuery` you should not be passing a `$sort` as part of the pipeline:
https://github.com/Novusphere/discussions-app/blob/master/novusphere-js/discussions/service/discussions.ts#L574

So for example, the equivalent here would be:
```js
            const query = await nsdb.search({
		sort: 'recent',
                key,
                cursorId,
                count,
                limit,
                pipeline: [{ $match: searchQuery } ],
            })
```

Options are: `recent`, `popular`, `controversial`
Previously, all the queries were using the equivalent of `recent`.

**Comment by samosaboy** [comment]
Added
