### ISSUE TITLE
Trending Tags

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#223]
The atmos DB node the front end is connected to should be able to supply a list of trending tags. Trending tags are sampled over the course of a 72-hour period where the most frequently used 10 tags are considered trending.

The tag `#tip` is excluded from this list (on the front end).

**Comment by Novusphere** [comment]
http://atmosdb.novusphere.io/discussions/search/trendingtags

Removing back end tag

**Comment by samosaboy** [comment]
Added in 2c802d512ba3fcd8f9b29e760cb1a59221bb5661
