### ISSUE TITLE
Add EOS Account Creation to Unified ID Wallet

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#230]
This process allows the creation of an EOS account payable in EOS or other supported partner tokens. The process for where the EOS comes from in the case of using a partner token is TBD.

**Comment by bluabaleno** [comment]
UI/UX will still need to be added for this

**Comment by Novusphere** [comment]
As mentioned in DM, this is basically reskin of withdrawal. The form needs the following:

- Account name
- Public key
- Fee

The public key by default should be set to the wallet public key from their Unified ID.
The fee by default should be 0.5 EOS
NOTE: In the future, the fee will be payable in other tokens held on their Unified ID but for now is EOS only.

Upon submission, a withdrawal is done to the EOS account `signupeoseos` with a memo like `testtestte11-EOS7THCLXfka4nCfAS5By1kaWvtkwcURCPLm2KSv4DxxsJuaNNuzr` which is `${account}-${publickey}`

It should be explained to the user the fee is used to pay for initial EOS resources (RAM, CPU, NET) and any excess from the fee will be forwarded to the user's newly created EOS account. No commission is taken by Discussions for account creation.
