### ISSUE TITLE
Readd meta tags for SEO

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#232]

**Comment by Novusphere** [comment]
https://discussions.app/tag/eos/2x4h2rj2gkn38/crypto_lions_prometheus_vs_eos_file_store_crypto_journalism_sucks

Title incorrect shows "CryptoLion's" instead of full title.
Regarding post body content, convert markdown to html and then take the "text" extract of the html.

**Comment by samosaboy** [comment]
Resolved in cf0ae745a1223fa7a2dd7cfc547b35ebdb4c1433
