### ISSUE TITLE
[Safari] Resource related to tokens isn't being loaded

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#236]
<img width="760" alt="Screen Shot 2020-02-24 at 2 56 15 PM" src="https://user-images.githubusercontent.com/14120416/75162708-dd7b5a80-5715-11ea-9d3a-b01a33759906.png">

**Comment by bluabaleno** [comment]
Also tipping and token balances don't seem to be working...

**Comment by Novusphere** [comment]
This seems to be all a result of site json not being loaded for you. When you refresh, is this problem solved?

**Comment by Novusphere** [comment]
https://github.com/Novusphere/discussions-app/blob/master/novusphere-js/eos/tokens.ts#L24

fetch api is used here

https://github.com/Novusphere/discussions-app/blob/3a47f2d6e2917d0077f10c8bc47e7a7f015dfd00/novusphere-js/discussions/service/discussions.ts#L426

axios api is used here



----

Conclusion: It seems the fetch() api is causing this error, where as axios doesn't seem to have this problem. `/site` seems to work fine, but `/site/tokens` doesn't. 

Please change all fetch() calls to axios.

**Comment by samosaboy** [comment]
Resolved by removing `node-fetch`.
