### ISSUE TITLE
Need more reliable way of processing oembed content instead of setTimeout

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#237]
once all the HTML is on the page from loading the thread/posts, etc. then it's safe to call the process() fns, but right now with setTimeout we're just guessing if that condition has been met

**Comment by samosaboy** [comment]
`refreshIFrames()` will get called once oembed is set, which should trigger a DOM update anyways due to state change, so lets see if this works as a permanent solution.

**Comment by Novusphere** [comment]
Reopened since issues still occuring
