### ISSUE TITLE
[SEO] Escape and process text for description/titles of threads

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#239]
See: 

![image](https://user-images.githubusercontent.com/39639828/75183207-0698ec80-5710-11ea-8cbf-0c4fef6d6726.png)

Notice that the title is wrong, this is due to the " character not being escaped.

Notice as well that the description is not escaped as when you look at the link you can see unescaped characters. 

For the description of posts we should first convert the markdown to html, then extract the plain text from the html. This can be done using the package `html2plaintext` see documentation for an example on how to use this package.

The description should contain the full post content for SEO purposes.

**Comment by samosaboy** [comment]
Resolved with https://github.com/Novusphere/discussions-app/issues/232
