### ISSUE TITLE
home is blank and there is no clear way out

### ISSUE THREAD

**Issue by fixedelineation** [Novusphere/discussions-app#24]
<img width="1211" alt="Screenshot 2019-10-23 20 34 24" src="https://user-images.githubusercontent.com/17442082/67451256-c516fa00-f5d4-11e9-96b0-d1460169f968.png">

to recreate
click on profile then click home

**Comment by samosaboy** [comment]
This is now resolved as of 7a795d8c207c1cae18b7931ac396270e2b3f1838
