### ISSUE TITLE
Notifications from watched thread where watcher is not OP doesn't work correctly

### ISSUE THREAD

**Issue by samosaboy** [Novusphere/discussions-app#245]
Not sure if I should open a new issue for it but I don't seem to be getting the notifications from watching a post

_Originally posted by @bluabaleno in https://github.com/Novusphere/discussions-app/issues/241#issuecomment-590938750_

**Comment by samosaboy** [comment]
I was unable to reproduce this since I have been getting notifications. Can you confirm if you see threads being watched under `Settings > Content > Watched Threads`? @bluabaleno

**Comment by bluabaleno** [comment]
oh ok. didn't know that tab was added. Will try it now

**Comment by Novusphere** [comment]
Reproduction of this issue:
	- User A creates a thread
	- User B follows/watches the thread
	- User C makes a post in the thread
	- A receives a notification
	- C doesn't receive a notification (despite following the thread)
