### ISSUE TITLE
Editing bug, text randomly disappears...

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#247]
![ezgif-6-4070980ea0d8](https://user-images.githubusercontent.com/14120416/75352692-11838680-58a2-11ea-9dd0-7d500f900284.gif)

Not much information I know, will try to update the issue as I document more encounters with it.

**Comment by samosaboy** [comment]
@bluabaleno were you able to encounter this again?

**Comment by bluabaleno** [comment]
yep.

**Comment by samosaboy** [comment]
Should be resolved in 7f2785cf72b850cc5a6767c16b360fc5a201eba6
