### ISSUE TITLE
YT link not embedding video.

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#251]
Link to the post:
https://discussions.app/tag/eos/2dmqfl2gymheg/eos_reduces_inflation_by_80

**Comment by Novusphere** [comment]
@samosaboy https://www.youtube.com/watch?v=6Ea-2LNW_T4&t=1s is the link posted:

https://atmosdb.novusphere.io/cors?https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=6Ea-2LNW_T4&t=1s&format=json

seems to return an OK payload.

**Comment by Novusphere** [comment]
Backend API has been updated to support "malformed" youtube URL: 

https://atmosdb.novusphere.io/cors?https://www.youtube.com/oembed?url=https://www.youtube.com/watch?t=1s&v=6Ea-2LNW_T4&format=json
