### ISSUE TITLE
Clicking "share" button opens bloks.io block explorer link

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#258]

**Comment by samosaboy** [comment]
Unable to reproduce

**Comment by Novusphere** [comment]
go to any thread: https://discussions.app/tag/eos/x4pqi4isnceb/wanchain_does_cross_chain_trx_with_eos

and click:
![https://cdn.discordapp.com/attachments/628358780421406755/685189298886410329/unknown.png]()
