### ISSUE TITLE
Unable to sync account data

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#259]
![photo_2020-03-09_15-22-40](https://user-images.githubusercontent.com/14120416/76247302-34fde800-6237-11ea-801c-6611327d5128.jpg)

Been getting a lot of these when I open up discussions lately. 

it's happening both on mobile and on desktop.

**Comment by bluabaleno** [comment]
Doesn't affect anything notable. Maybe messes up the notifications...

**Comment by samosaboy** [comment]
Removed popup, now it is in the console and added extraneous checks to make sure the error isn't due to some missing/undefined data.

**Comment by bluabaleno** [comment]
Users are still experiencing the issue...
![Uploading photo_2020-03-18_13-03-05.jpg…]()

**Comment by samosaboy** [comment]
@bluabaleno is this user's account data not synced in that current browser? Those console error messages seem un-related to the website.

**Comment by bluabaleno** [comment]
I've been getting more and more of the same error as well.

<img width="1436" alt="Screen Shot 2020-03-23 at 11 03 23 AM" src="https://user-images.githubusercontent.com/14120416/77310273-f74c9500-6cf5-11ea-9fc6-181f080459f7.png">

**Comment by samosaboy** [comment]
Prod build was still using minified build, seems like it is unminified now. @bluabaleno can you try screenshotting the same error again?

**Comment by samosaboy** [comment]
Issue was caused by size limit (10kb). Since bumping that up to 256kb it is now resolved.
