### ISSUE TITLE
Editing bug - txt jumbles up when editing long posts.

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#262]
![Screen-Recording-2020-03-11-at-7](https://user-images.githubusercontent.com/14120416/76454651-eeda8d00-63cc-11ea-8465-57652d00afbc.gif)

<img width="1321" alt="Screen Shot 2020-03-11 at 7 10 57 PM" src="https://user-images.githubusercontent.com/14120416/76454168-111fdb00-63cc-11ea-8c38-7da752daaa9b.png">

**Comment by bluabaleno** [comment]
ok I seem to discovered what cause the bug. It only affects posts that with heading formats (H1/H2).

**Comment by samosaboy** [comment]
Should be resolved in 7f2785cf72b850cc5a6767c16b360fc5a201eba6
