### ISSUE TITLE
Pinning and unpinning post works weird

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#265]
I see posts pinned but when I go to unpin it it doesn't allow me.

![ezgif-2-2eb7845ca61e](https://user-images.githubusercontent.com/14120416/76549266-03c82680-6488-11ea-85df-aa92f3a2c8e5.gif)

**Comment by samosaboy** [comment]
Was not able to re-produce, can you be more specific? I tried the exact steps and was able to unpin and pin as expected.

**Comment by bluabaleno** [comment]
I think it might because I have delegated another person as a moderator of that tag.

**Comment by bluabaleno** [comment]
I'm not sure as well. But this was the post in question.

https://discussions.app/tag/atmos/156ykvxoo4k2u/up_for_discussions_discussions_2_5_features_eos_disk_and_privacy_and_reddit_censorship_turns_up_to_11

**Comment by boid-com** [comment]
https://discussions.app/tag/boid 
Many pinned items, I found when I refresh the page then the list of pinned items can change sometimes. Often it seems like it's unpinned then I check back later and it's still there?

**Comment by Novusphere** [comment]
This issue should be resolved now @boid-com @bluabaleno  please let us know if it's not. Closing for now.
