### ISSUE TITLE
UI/UX low hanging fruit changes

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#288]
- Moving trending tags to the right of the posts (current on left) along with Footer
- When "+ New Post" is selected, if no tag is selected by default it should select "#all" so that the user isn't forced to select a tag
- Make titles optional, not mandatory, put "(optional)" in the title place holder
- Add a "see all" for trending tags that shows top 100 trending tags: http://atmosdb.novusphere.io/discussions/search/trendingtags?days=30&count=100

**Comment by bluabaleno** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UI/UX cues from Commun.com](https://trello.com/c/S7iIqAIY/18-ui-ux-cues-from-communcom)
