### ISSUE TITLE
No post confirmation when posting without title 

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#290]
![ezgif-7-7fca1862c5ae](https://user-images.githubusercontent.com/14120416/78514156-d7ae7580-77a7-11ea-8292-b479e9b3761b.gif)

**Comment by Novusphere** [comment]
Relavent images below:

![](https://cdn.discordapp.com/attachments/628358780421406755/696571853937836093/unknown.png)

https://bloks.io/transaction/0eed76844f1db5fe96119ef53f0b1aba60d2a34b53dee276812c384868836177

shows up in https://discussions.app/tag/test ok

when clicking it, url is https://discussions.app/tag/test/8678r4fcjm00/#752923ff-408c-41b8-9c95-42aa71edddee so it thinks its a permalink?
