### ISSUE TITLE
Post content preview enhancement

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#291]
Right now, we use a cut-off so that post content that is too long doesn't fully appear. However, this prevents inlined content from showing, i.e. a post might just be a Twitter link but the inlined Tweet doesn't fully show because it's cut off.

To easily address this we adopt a Twitter like mechanism.

If `post.content.length <= 300` then do not cut off the post content. Otherwise, treat it as we treat all posts currently.

**Comment by bluabaleno** [comment]
Please make sure double chin tweets (tweets with a reply attached to it) are supported 🙏. 
I.e:
https://twitter.com/BBCBreaking/status/1247249548931747840?s=20

**Comment by bluabaleno** [comment]
The tweets are still not fully showing:
<img width="624" alt="Screen Shot 2020-04-07 at 11 50 42 AM" src="https://user-images.githubusercontent.com/14120416/78661175-38cc6b00-78c6-11ea-81d9-173d92734567.png">
versus 
<img width="648" alt="Screen Shot 2020-04-07 at 11 53 33 AM" src="https://user-images.githubusercontent.com/14120416/78661307-716c4480-78c6-11ea-9905-a27214f807af.png">

**Comment by samosaboy** [comment]
Fixed.
