### ISSUE TITLE
Images not showing correctly / at all

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#311]
images aren't showing

https://discussions.app/tag/atmos/p9dfukjxsa7y/minor_ui_comments_and_actionable_suggestions#88848fca-336a-41f9-947d-113f8953a084

from bloks transaction:
```
content: As for Sign-in... [https://atmosdb.novusphere.io/discussions/upload/image/1588151566931.png](https://atmosdb.novusphere.io/discussions/upload/image/1588151566931.png) How is this? [#tip](/tag/tip) 100 ATMOS
```

https://atmosdb.novusphere.io/discussions/upload/image/1588151566931.png is a valid image

Brave DOM examination:

https://cdn.discordapp.com/attachments/628358780421406755/706943299944054794/unknown.png

Firefox DOM examination:

https://cdn.discordapp.com/attachments/628358780421406755/706944976210362468/unknown.png

**Comment by samosaboy** [comment]
Removed react lazy loading component, found a Github issue related to it. https://github.com/Aljullu/react-lazy-load-image-component/issues/42

Seems like it was "fixed" but it has come back.
