### ISSUE TITLE
Post content "flickers"

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#315]
Possibly as a result of trying to load new content and reprocessing the thread?

example:
https://discussions.app/tag/all/3mfjldht3jdaq/

**Comment by Novusphere** [comment]
Even more of an issue when trying to pin a post, the dialog from clicking the "..." goes away when a post flickers.

**Comment by samosaboy** [comment]
Investigated more: issue is coming from <Replies> and `post.tsx` being re-rendered due to the new 'real-time replies' feature. I've reverted and deployed it for now until I fully resolve this issue.

**Comment by samosaboy** [comment]
Fixed in https://github.com/Novusphere/discussions-app/pull/320
