### ISSUE TITLE
post options won't stay open

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#317]
![ezgif-3-25ddaa381a86-2](https://user-images.githubusercontent.com/14120416/81322469-f1cfc200-908b-11ea-8a8a-bc8ccda74879.gif)

**Comment by Novusphere** [comment]
this is the same bug as #315

**Comment by samosaboy** [comment]
Fixed in https://github.com/Novusphere/discussions-app/pull/320
