### ISSUE TITLE
Scrolling bug?

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#332]
I'm not sure what's up with this but I'm on this thread: https://discussions.app/tag/atmos/1seqd0ud2wsgm/discussions_app_crossword_puzzle

and if I scroll the bottom and then just wait long enough (like ~20s? idk) it scrolls all the way to the top automatically

**Comment by samosaboy** [comment]
Fixed in https://github.com/Novusphere/discussions-app/commit/75421c859a3a24fb00af863e6912ad5eb0413828#diff-c82f65945b970cb320b9200029450566R639
