### ISSUE TITLE
Searching for hash tags doesn't work

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#333]
https://discussions.app/tag/atmos/1243q6dxhdn36/discussion_app_search_bar_hashtag

This is a problem likely stemming from the "#" being in the URL. It doesn't seem the search is correctly preformed. Tested on backend the clause `{"$text":{"$search":"#atmos"} }` which finds matches but on front end "#atmos" doesn't. Haven't looked at network traffic.

**Comment by samosaboy** [comment]
Encode/decoded uri to solve this issue
