### ISSUE TITLE
Replies are blocked by the expand text input box

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#335]
When you post a reply on a post, the reply is pushed down by the input box and becomes hidden.

![ezgif-4-5c5684b429c4](https://user-images.githubusercontent.com/14120416/83020406-58f3ed00-a020-11ea-8716-652f19ccc377.gif)

**Comment by samosaboy** [comment]
After disabling https://github.com/Novusphere/discussions-app/issues/347 this seems have to been resolved. @bluabaleno can you confirm if you still experience this?

**Comment by bluabaleno** [comment]
@samosaboy nope, replies are showing up fine now 👍
