### ISSUE TITLE
Previews not showing on mobile 

### ISSUE THREAD

**Issue by fixedelineation** [Novusphere/discussions-app#349]
![010F86C6-2074-4ECA-BAD9-825527E1DA42](https://user-images.githubusercontent.com/17442082/83955657-0ed1ef00-a80a-11ea-9db3-2fcadbea50c6.png)

**Comment by Novusphere** [comment]
This is because the branch on beta was the mod policy branch, which does not have the mobile changes. These branches will be merged later and deployed.
