### ISSUE TITLE
Blocked / Spam support list in Settings for new mod pol 

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#355]
endpoint eg

https://atmosdb.novusphere.io/discussions/moderation/spam?mods=EOS7yBvx7mSApiyKPWzgpU3Xs6Em66WhkdYpM9Exon4rmeikBefZf&domain=https://discussions.app

**Comment by samosaboy** [comment]
Added in https://github.com/Novusphere/discussions-app/commit/29a30b218172dc3289341b114c6ec4162ca1d6b1
