### ISSUE TITLE
Hash tags not being parsed properly

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#36]
Tags are not being parsed properly, for example this post https://beta.discussions.app/e/test/1aznlu2okufgi/spaghetti has "#spaghetti" and is posted in "test" so it should have the tags "test" and "spaghetti" but in the block explorer, it shows it only has "test" 

https://eosq.app/tx/55d565a02fe1d126550cf33e69ef0167db51284ed0d2f2cd841aaa0e305a500a

**Comment by samosaboy** [comment]
Added recently.
