### ISSUE TITLE
mobx invariant error when posting

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#41]
See:

https://i.imgur.com/pTr6uHI.png
thread: https://beta.discussions.app/tag/test/13fa22qcdvmjh/hallelijeh

Note:

Posts still go through and reach the blockchain and is handled correctly by the server but due to the error, the post doesn't show up in the thread when clicking "post reply" and instead this error is triggered.

**Comment by samosaboy** [comment]
Fixed in https://github.com/Novusphere/discussions-app/commit/7bb76bc8282c379888f1df8cfb18ba2c6b1ca043
