### ISSUE TITLE
Posting preview is strange

### ISSUE THREAD

**Issue by fixedelineation** [Novusphere/discussions-app#45]
The formatting seems off on a post I pasted from a word doc. There are strange underscores before some letters and words are getting cut up at line breaks.
Text as it appears in Editor
<img width="1034" alt="Screenshot 2019-11-12 21 24 55" src="https://user-images.githubusercontent.com/17442082/68735674-4d187000-0593-11ea-9b92-3a87e8b98086.png">

preview text
<img width="1018" alt="Screenshot 2019-11-12 21 24 33" src="https://user-images.githubusercontent.com/17442082/68735675-4d187000-0593-11ea-9926-a0bbd1f5ea12.png">

Text in Editor
<img width="1039" alt="Screenshot 2019-11-12 21 24 17" src="https://user-images.githubusercontent.com/17442082/68735676-4d187000-0593-11ea-9936-a484c7a7f531.png">

Preview
<img width="1019" alt="Screenshot 2019-11-12 21 23 59" src="https://user-images.githubusercontent.com/17442082/68735677-4db10680-0593-11ea-96f6-d5914f64e286.png">

published post
https://beta.discussions.app/tag/novusphere/1jl5evl8ggbf4/discusssions_app_white_paper

**Comment by fixedelineation** [comment]
might be widespread issue 

<img width="736" alt="Screenshot 2019-11-12 21 33 57" src="https://user-images.githubusercontent.com/17442082/68735991-49391d80-0594-11ea-93f9-9aac8b5236ad.png">

https://beta.discussions.app/tag/novusphere/8t9devow1bzw/brian_key_vs_password

**Comment by samosaboy** [comment]
Seems to be italics causing this issue

**Comment by samosaboy** [comment]
Wasn't able to reproduce this bug.

Could you tell me exactly how you got that bug?

What i did:
1. Create a word doc with text and random italic words
2. Copy the entire contents of the word doc into a post
3. Submit post

I saw no `_` in the post.

**Comment by Novusphere** [comment]
@samosaboy Look at for example the sentence "Your posting private..." in the 2nd picture. The word "each" is broken over two lines which looks clunky.

**Comment by Novusphere** [comment]
If this is not fixed, please reopen this issue/comment @fixedelineation
