### ISSUE TITLE
Replies are no longer automatically including the parent poster pk in mentions field

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#53]
https://bloks.io/transaction/cf958d3bc2f70206ac01cb2c9087a8f497220ad67928b3c34cf797ca9dd6d6bd?tab=raw

https://beta.discussions.app/tag/uxfyre/385bpob832djv/asdfasdf#comments

This is the "hi Brian" post

**Comment by samosaboy** [comment]
Fixed in d80d5e67c766622abcc33f1873edd9473f206938

but I won't close this ticket until we confirm that it is working as intended

**Comment by Novusphere** [comment]
Closing ticket as we've confirmed this works as intended.
