### ISSUE TITLE
Change this logo

### ISSUE THREAD

**Issue by fixedelineation** [Novusphere/discussions-app#59]
The login logo is scatter still, we need to change it
<img width="668" alt="Screenshot 2019-11-16 16 20 01" src="https://user-images.githubusercontent.com/17442082/69001037-0c6b7000-088d-11ea-9db0-24be4cf41da7.png">

Brian should whip something up for now

**Comment by Novusphere** [comment]
![](https://i.imgur.com/zWB4Kol.jpg) @samosaboy

**Comment by samosaboy** [comment]
Added in 8c17ebe64ff934852b3db68f4be07a8944726ec7
