### ISSUE TITLE
Follow ("watch") a thread

### ISSUE THREAD

**Issue by samosaboy** [Novusphere/discussions-app#6]
We need to add a 'watch' feature to a post so a user can get notifications/alerts when that post has been modified or a thread has a new post.

**Comment by Novusphere** [comment]
When a thread is "watched" perhaps keep the most recent post time in a local storage (post ID, time) kvp. Then the client can on a timer re-request the most recent post and compare the time and if there's a newer post the user is alerted. Perhaps limit this to 10 threads being watched or something being watched so the server isn't being spammed as much.

**Comment by Novusphere** [comment]
When a thread is watched, in the local storage object saved to the server create a data structure which retains the thread id (as used in the URL) and the last recorded `totalReplies` for a thread. Occasionally, you can then query nsdb to see whether `discussions.getThreadReplyCount()` is greater than the value recorded in ls. If it is, the post has new replies in it that the user/watcher hasn't read yet. From this, we can then create a notification.
