### ISSUE TITLE
Minor icon changes

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#62]
- Change "edit post" to a pencil icon (but mouse over says edit post)
- Change "watch post" to an eye (but mouse over says watch post)
- Change the eye icon to a chain icon (block explorer link)
- Change the chain icon to the "share icon" 

The "share icon" should expand out into various options such as:

- permalink
- twitter
- etc (the above is ok for now, more to add later)

![image](https://user-images.githubusercontent.com/39639828/69083173-980d0a00-0a0f-11ea-9592-1a0504b01ef2.png)

(ignore the blue circled area, refer to the picture for the "Share icon / section")

**Comment by samosaboy** [comment]
Added Twitter share in e2aa4653860d8eb80478a5164fbb29e46151e3b4
