### ISSUE TITLE
"Normalize" links in posts

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#63]
https://beta.discussions.app/tag/teamgreymass/2bpupxf6kn9q7/chat_with_eos_thinkers_jest_and_myles_of_greymass

This post was made by copying a description on youtube. How hard would it be to make it so that if a text is a link, to make it so the link is that link as well?

i.e. if there was some website that had the text https://google.com/ but linked to https://yahoo.com/, the pasted text would just link to https://google.com/, not yahoo.com

**Comment by samosaboy** [comment]
Added in bb48dda71461e23449787ba82fedc7e7659346ac
