### ISSUE TITLE
When in "New Post" selecting a new tag/sub erases written post content

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#65]

**Comment by samosaboy** [comment]
This is actually quite an extensive solution, the problem is re-rendering caused by react-select and the form component having deps to the select options. Will have to find a solution.

**Comment by Novusphere** [comment]
@samosaboy Consider as a "simple solution" disabling writing anything (title/content) until it's selected with a clear message telling them that they first need to select a tag... but this does need to be resolved at some point.

**Comment by samosaboy** [comment]
Fixed in 5b41f3191f7d70be999f5719e8d6320ed39e00e6
