### ISSUE TITLE
Inline Content

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#66]
# OEmbed

Convert OEmbed content into their respective HTML and inject into the post body content. Below is a list of all OEmbed content that should be supported. Use `nsdb.cors()` to resolve as not all OEmbed endpoints provide the CORS header.

- Youtube `https://www.youtube.com/oembed?format=json&url=https://www.youtube.com/watch?v=NJkQzZOdOsI` -- **Note** multiple domains here: youtube.com, www.youtube.com, youtu.be must be resolved to their `www.youtube.com/watch?v=` equivalent
- Imgur `https://api.imgur.com/oembed.json?url=https://imgur.com/gallery/6EJqo`
- Twitter `https://publish.twitter.com/oembed?url=https://twitter.com/thenovusphere/status/1196955063933161472`
- DTube `https://api.d.tube/oembed?url=https://d.tube/v/thecastle/pltz5yir`
- Soundcloud `https://soundcloud.com/oembed?format=json&url=https://soundcloud.com/quigginreport/quiggin-report-38`
- Instagram `https://api.instagram.com/oembed/?url=` -- **Note** this works for all instagram links afaik: instagram.com, www.instagram.com, instagr.am
- Facebook `https://www.facebook.com/plugins/post/oembed.json/?url={content-url}`

# Non-OEmbed

- Bitchute (see https://github.com/Novusphere/eos-forum/blob/dev/src/types/post/attachment.js#L138 and generate an iframe)

# Non-OEmbed (Telegram)

`https://t.me/greymass/4312` --> `greymass/4312`

https://github.com/Novusphere/eos-forum/blob/dev/src/components/core/PostAttachment.vue#L102

Note `telegram()` is a function from `telegram.js` see below,

https://github.com/Novusphere/eos-forum/blob/dev/src/components/core/PostAttachment.vue#L18

You want to set a "random id" to the div, because of the hack used here,
https://github.com/Novusphere/eos-forum/blob/dev/src/telegram.js#L62

You'll want to use the telegram.js I've "hacked" as without this hack, the same instagram post will not load twice on the same document. You can compare this with their original telegram.js as they may have fixed the issue.

# Images

Images should automatically display from links. See
https://github.com/Novusphere/eos-forum/blob/dev/src/types/post/post.js#L412

**Comment by samosaboy** [comment]
Added
