### ISSUE TITLE
Visual indicator for when a post is being watched

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#68]
Maybe color the eye icon differently?

**Comment by samosaboy** [comment]
Added in ad47c971649752e51364ad4e531e99b7a3433bfa

**Comment by bluabaleno** [comment]
The color in correct but the eye is of the crossed out one instead of the regular.

**Comment by samosaboy** [comment]
Fixed in 0c23f44307fa1738cc32e51b3520d9da9290e2d4
