### ISSUE TITLE
Save persistent account data for post key to server for cross device restoration

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#75]
Account data, such as subscribed subs, watched threads, etc. should be saved whenever changes are made to the connected discussions server. This allows for if the user starts using a new device, the data can be restored.

See `nsdb.getAccount(pk)` and `nsdb.saveAccount(pk, obj)`

**Comment by Novusphere** [comment]
Now possible to implement now that #34 has been closed.

**Comment by samosaboy** [comment]
Added in 42b7b168fc2963b75c2f1697316a616cd423ec30
