### ISSUE TITLE
Inline Content - Do not inline Twitter profiles, only tweets

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#76]
i.e. `https://twitter.com/zZCastleZz` should not be inlined

https://beta.discussions.app/tag/general/avrzc7aqbv65/coppa_is_absolute_bullshit_to_the_highest_order

Related to #66

**Comment by samosaboy** [comment]
Added in 5b0b3afdeb56cb5eef84123813e85ea8e2d4aee5
