### ISSUE TITLE
Inline Content - Instagram Embed Process must be called after all posts loaded

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#77]
See: https://github.com/Novusphere/eos-forum/blob/dev/src/components/core/PostAttachment.vue#L94

This either must be called everytime an instagram attachment shows in the thread, or at the end of loading the thread and all post content.  If this isn't called, the instagram embed will not display properly.

Related to #66

**Comment by samosaboy** [comment]
Added in 1968a717558ba3cef674f94d79a64f2b38292d1d
