### ISSUE TITLE
setTimeout refreshIFrames is not reliable

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#81]
Sometimes, it gets called to early which means the inlined content doesn't load correctly, see...

![image](https://user-images.githubusercontent.com/39639828/69499211-cb431380-0ebd-11ea-848b-00bbb553d533.png)

https://github.com/Novusphere/discussions-app/blob/9e91efc0915a7fa87161640d824216fc6e04b393/components/rt-preview/rt-preview.tsx#L84

**Comment by Novusphere** [comment]
Consider the following as an example:

Consider something like the following,

```js
async waitForObject(o, withObject, tries=30) {
	let obj = o();
	if (obj && withObject) {
		withObject(obj);
	}
	else if (tries > 0) {
		setTimeout(() => waitForObject(o, withObject, tries-1), 1000);
	}
}
```


```js
} else if (href.match(/twitter/)) {
		
  waitForObject(() => (window as any).twttr, (twttr) => {
		twttr.widgets.load();
	});
} 
```

**Comment by samosaboy** [comment]
I think I managed to solve this issue by using useEffect twice with state dep https://github.com/Novusphere/discussions-app/commit/d7798e223a6f11ad3d9477f478050092a90dc277#diff-3312c0ccae279a7869e8f4f306afaebaR123
