### ISSUE TITLE
Limit number of non-image inlined content

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#82]
For posts, this can be set to something high like 20 so that articles can be written or blog posts. However, for replies this should be limited to something like 3 to prevent spam/clutter.

**This is an open discussion, not a planned limitation/feature at this time**

Examples of inlined content can be seen here:
https://beta.discussions.app/tag/test/25gcl24b824w4/oembed_testing_here

**Comment by samosaboy** [comment]
Added in c39ac52c3aa6c60a0125cc053b20d6d9210d94e4
