### ISSUE TITLE
Tag list in "New Post" displays incorrectly and should allow user to type in their own tag arbitrarily

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#83]
After creating new tag from the left column, when creating new post in tag, the newly created tag is no where to be seen.

**Comment by Novusphere** [comment]
We need a link to the post you made, or the transaction id, or even the tag name. This is not enough information.

**Comment by Novusphere** [comment]
@samosaboy When you add a tag using the "+" on the left, it's not appearing as an option in the tag list you get when creating a "New Post" (top right). Further, "New Post" should let you arbitrarily type in a tag, rather than forcing you to **only** chose from the list it provides.

**Comment by samosaboy** [comment]
Added in 6aa500fce95566a83563e25ca8736e2d631ccf1f
