### ISSUE TITLE
embed telegram message not fully showing

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#86]
https://beta.discussions.app/tag/everipedia/133cmprnyvn8t/everipedia_launches_iq_fund_for_community_projects

**Comment by bluabaleno** [comment]
huh.... weird. Sometimes it shows the whole thing and sometimes it doesn't

**Comment by samosaboy** [comment]
Fixed in 3c452ec8990d931618ee19d7c4970813ed2a9d60
