### ISSUE TITLE
Better tag parsing

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#88]
https://eosflare.io/tx/AC32EA5F9A783F05A6CED100B0033C5B21335EC3D1D14B823A20470EA3B259E2

"###", and also not sure if there's handling for not accidentically treatnig links like "abc/#123/lol" as a tag and extracting "#123"... to do this you can match an additional character on both sides (l/r) and trim for whitespace. Then see if the string still satisfies "What is a tag", for example

`"hello #abc 123"` -> `" #abc "` -> `"#abc"` -> yes this is a tag
`"#hello abc 123"` -> `"#hello "` -> `"#hello"` -> yes this is a tag
`"/hello/#abc/123"` -> `"/#abc/"` -> `"/#abc/"` -> no this isn't a tag

**Comment by Novusphere** [comment]
It would be nice if we could support non-latin tags, i.e. "#日本" but this isn't required if tricky.

**Comment by samosaboy** [comment]
Hash matching has been fixed in b1351a453b8a7333546365dd515999d8795601fc

Will not add non-latin tag support just yet.
