### ISSUE TITLE
Edits some time do not actually "work"

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#90]
it seems sometimes the edit is made visually to the user, but then if they refresh it's not there, as well, if they check on chain it's not there -- so either the server rejected it for some reason, or it was never sent to the server to add to chain

**Comment by samosaboy** [comment]
Added console logs to debug this a bit better 74b148d3a018b010f2b6b1f86bb03312a92389ac

**Comment by bluabaleno** [comment]
edits seems to work now but there's a strange UI bug @samosaboy 
![image](https://user-images.githubusercontent.com/14120416/70620108-4a4e8080-1c0e-11ea-80f4-08226132c628.png)

**Comment by bluabaleno** [comment]
Just tried editing again, and got some errors this time.

![editing error](https://user-images.githubusercontent.com/14120416/70621646-fe9dd600-1c11-11ea-80da-a73b4fa79d3b.JPG)

**Comment by samosaboy** [comment]
I wasn't able to reproduce any of the bugs above, I tried

1. Creating a reply, then editing it immediately.
2. Creating a thread and editing the OP immediately.
3. Creating a reply to an existing thread and editing that.

In all 3 cases, I was able to successfully see my edits upon refresh and waiting 2-5 seconds.

I have added console logs to OP edits as well, so we can use that to debug. But I was able to confirm that the edits went through, however, it appears there might be a case(s) where the edit does not go through.

**Comment by bluabaleno** [comment]
> I wasn't able to reproduce any of the bugs above, I tried
> 
> 1. Creating a reply, then editing it immediately.
> 2. Creating a thread and editing the OP immediately.
> 3. Creating a reply to an existing thread and editing that.
> 
> In all 3 cases, I was able to successfully see my edits after waiting 2-5 seconds and refreshing.
> 
> I have added console logs to OP edits as well, so we can use that to debug. But I was able to confirm that the edits went through.

hmmm that's strange, maybe it has something to do with my browser? I'm getting these errors quite often.

**Comment by Novusphere** [comment]
Maybe we should add a notification like "Edit successful"

**Comment by bluabaleno** [comment]
So I got the confirmation message yet still, when I refresh the page after, the edits are lost.
![image](https://user-images.githubusercontent.com/14120416/70802647-e2cd3800-1da9-11ea-97e5-35183fe40c89.png)

**Comment by Novusphere** [comment]
Wait at least 5-10 seconds and check if the message hasn't been updated, if that's the case then please include the transaction id of the edit on chain.

**Comment by samosaboy** [comment]
Added in 04b9c9751ef0f378dd8882f847bae7c1f2337bbd

Editing a post will wait 5 seconds before completing on the UI, will still submit to the API before.

**Comment by bluabaleno** [comment]
I'm having the same issue again. This time on a different laptop with a different browser (Safari on Mac)

![edit bug](https://user-images.githubusercontent.com/14120416/73491164-e478ac80-43a5-11ea-8c6e-d3fee1bf6a36.gif)
<img width="1440" alt="Screen Shot 2020-01-30 at 9 14 27 PM" src="https://user-images.githubusercontent.com/14120416/73491179-ed697e00-43a5-11ea-89eb-df9ab0bd9f0d.png">

**Comment by Novusphere** [comment]
Doesn't look like the edit ever hit the chain... Can we make edits display the TXID as part of the success message? @samosaboy
