### ISSUE TITLE
Firefox loading issue

### ISSUE THREAD

**Issue by fixedelineation** [Novusphere/discussions-app#92]
I can't get the beta to load in Firefox
<img width="1278" alt="Screenshot 2019-12-06 07 35 34" src="https://user-images.githubusercontent.com/17442082/70334869-1680ee80-17fb-11ea-9243-6a56a763a0a3.png">
<img width="353" alt="Screenshot 2019-12-06 07 37 47" src="https://user-images.githubusercontent.com/17442082/70334977-52b44f00-17fb-11ea-8140-bc33dc1b9681.png">

**Comment by Novusphere** [comment]
Have you tried this on a different device? I normally do all my initial testing on Firefox and haven't had any issues with the beta.

**Comment by samosaboy** [comment]
Fixed in 70f885f37fe457e08c9ecb73f871ecd58b1b1b31
