### ISSUE TITLE
Airdrop Tool

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#93]
As provided, the airdroop tool should output a file similar to `eos-sendmany.json`

Accounts should be validated and this can be done using the EOS Cafe API:
"https://eos.eoscafeblock.com/v1/chain/get_table_by_scope" 
Request:
`{"code":"eosio","table":"userres","lower_bound":"novuspherei","upper_bound":"novusphereiz","limit":10}`
Response:
`{"rows":[{"code":"eosio","scope":"novusphereio","table":"userres","payer":"novusphereio","count":1}],"more":""}`

In this case, both upper_bound and lower_bound is the account name we test for validity. Assumingly, there will be `count: 0` or an error thrown if no account is found. **This should be conveyed to the user that there is an invalid name on their airdrop list.**

**Comment by samosaboy** [comment]
Added in 2750d2ce08f7eb7a6223b3587b158a35c1d4a21c
