### ISSUE TITLE
Create a threshold limit for airdrops to handle different cases (see desc)

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#97]
Set the threshold to 0 for simple testing, since producing `airdrops.json` works.

If the number of `recipients > the threshold` then produce the `airdrop.json` file.
Otherwise, try to connect to Scatter and perform the transaction from the web UI.

e.g. code below:
```js
    const result = await eos.transact(
        config.transfer.map(t => ({
            account: "novusphereio", // the token contract
            name: 'transfer',
            data: {
            	from: eos.auth.accountName, // the account sending the token
            	to: t, // the account receiving the token
            	quantity: "100.000 ATMOS", // the amount
            	memo: "this is a memo" // the memo
            }
        })));
```

`eos` is imported from novusphere js. Later the threshold may be changed to something like 100, so a "simple airdrop" can be done from the web browser, but a more complicated airdrop requiring multiple transactions will be done from a tool utilizing `airdrops.json`

**Comment by samosaboy** [comment]
Added in 8fc54f8a4f5cb722fce0e6617cfeae41f9cb7123. Still waiting clarification on above method usage.

**Comment by samosaboy** [comment]
Added both "Download Airdrop" and "Airdrop" button bcbdf50d199c066f55494c0dc1d97564ed0f8df0
