### ISSUE TITLE
Error message: "Post #xxxxx cannot be found"

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#99]
This error message pops up almost every time after I created a new post. The post shows up fine after I hit the refresh button but still, this would confuse a lot of first time users.

**Comment by Novusphere** [comment]
@samosaboy wait until the post has been added to atmos db before navigating to the newly created thread. That way, even if the user refreshes, it's already in atmos db.

**Comment by samosaboy** [comment]
Fixed in c744fa9f21571558a1fba6569405c01cdf43dc21

Now when creating a thread, every 2s after submitting it'll check if the post is made before re-directing.
